---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hola-cust-premium
spec:
  precedence: 2
  destination: 
    name: hola
  match:
    request:
      headers:
        x-cust-type:
          exact: "premium"
  route:
  - labels:
      version: "2.0"
    weight: 100